version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Data Processing Tests
          command: python -m unittest discover -s tests -p "test_data_processing.py"

workflows:
  version: 2
  build:
    jobs:
      - build
